#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

cd ../../plic/
wmake libso
cd ../plicBinIsoThermTransLLEFlowFoam/
wmake
cd ../plicIsoThermTransLLEFlowFoam/
wmake

# ----------------------------------------------------------------- end-of-file
