#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

cd SCF-core/src/
make
cd ../../plic/
wmake libso
cd ../plicAdvDiffIstFlowFoam/
wmake
cd ../plicIsoThermTransLLEFlowFoam/
wmake

# ----------------------------------------------------------------- end-of-file
