#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

cd ../../plic/
wclean libso
cd ../plicBinIsoThermTransLLEFlowFoam/
wclean 
cd ../plicIsoThermTransLLEFlowFoam/
wclean 

# ----------------------------------------------------------------- end-of-file
