#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wclean libso plic
wclean 
wclean plicTFoam
wclean plicFlowFoam
wclean plicDiffFoam

# ----------------------------------------------------------------- end-of-file
