
_DDELETE2_(idx_species);
_DDELETE2_(idx_groups);

_DDELETE2_(Pc);
_DDELETE2_(Tc);
_DDELETE2_(Vc);
_DDELETE2_(w);
_DDELETE2_(MW);
_DDELETE2_(dm);
_DDELETE2_(k);
_DDELETE2_(H8);
_DDELETE2_(Tb);
_DDELETE2_(SG);

_DDELETE2_(kij_T);
_DDELETE2_(kij);

_DDELETE2_(x_cellI_tmp);
_DDELETE2_(y_cellI_tmp);
_DDELETE2_(Dij1_tmp);
_DDELETE2_(Dij0_tmp);
_DDELETE2_(xs1_tmp);
_DDELETE2_(xs0_tmp);
_DDELETE2_(ys1_tmp);
_DDELETE2_(ys0_tmp);

_DDELETE2_(erfInv_table);
