#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wclean libso cellInfo
wclean libso Plane
wclean libso plicLeastSquares
wclean libso ../plicStencils
wclean libso

# ----------------------------------------------------------------- end-of-file
